version: "3.8"

services:
  postgres:
    image: postgres:13.2
    container_name: postgres
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - kangaroo-db:/var/lib/postgresql/data

volumes:
  kangaroo-db:
