version: "3.8"

services:
  kangaroo-server:
    image: ghcr.io/brian2509/kangaroo-server:latest
    container_name: kangaroo-server
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "5000:5000"
    network_mode: host
