version: "3.8"

services:
  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./nginx:/etc/nginx
    ports:
      - 80:80
      - 443:443

  server:
    image: ghcr.io/brian2509/kangaroo-server:latest
    container_name: server
    restart: unless-stopped
    command: "npm run start:prod"
    depends_on:
      - postgres
    env_file:
      - .env
    ports:
      - "5000:5000"

  postgres:
    image: postgres:13.2
    container_name: postgres
    restart: unless-stopped
    env_file:
      - .env
    ports:
    - "5432:5432"
    volumes:
      - kangaroo-db:/var/lib/postgresql/data

volumes:
  kangaroo-db:
