version: "3.8"

services:
  server:
    build: .
    container_name: server
    restart: unless-stopped
    command: "npm run start:dev"
    depends_on:
      - postgres
    env_file:
      - .env
    ports:
      - "5000:5000"
    volumes:
      - ./:/app
      - /app/node_modules

  postgres:
    image: postgres:13.2
    container_name: postgres
    restart: unless-stopped
    env_file:
      - .env
    ports:
    - "5432:5432"
    volumes:
      - giraffe-db:/var/lib/postgresql/data

volumes:
  giraffe-db:
