/* tslint:disable */
/* eslint-disable */
/**
 * Kangaroo Server
 * In order to interact with the API from this documentation alone follow the following steps: 1. Register at the register route. 2. Login using the credentials at the login route. 3. Get the `access_token` from the response and enter it in the Authorization formk. 
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { StickerRo } from './sticker-ro';
// May contain unused imports in some cases
// @ts-ignore
import { UserRo } from './user-ro';

/**
 * 
 * @export
 * @interface StickerPackRo
 */
export interface StickerPackRo {
    /**
     * 
     * @type {string}
     * @memberof StickerPackRo
     */
    'id': string;
    /**
     * 
     * @type {string}
     * @memberof StickerPackRo
     */
    'name': string;
    /**
     * 
     * @type {boolean}
     * @memberof StickerPackRo
     */
    'personal': boolean;
    /**
     * 
     * @type {boolean}
     * @memberof StickerPackRo
     */
    'animated': boolean;
    /**
     * 
     * @type {Array<StickerRo>}
     * @memberof StickerPackRo
     */
    'stickers': Array<StickerRo>;
    /**
     * 
     * @type {string}
     * @memberof StickerPackRo
     */
    'trayIconImageFileUrl': string;
    /**
     * 
     * @type {string}
     * @memberof StickerPackRo
     */
    'trayIconImageFileUrlOriginal': string;
    /**
     * 
     * @type {Array<UserRo>}
     * @memberof StickerPackRo
     */
    'members': Array<UserRo>;
    /**
     * 
     * @type {UserRo}
     * @memberof StickerPackRo
     */
    'author': UserRo;
    /**
     * 
     * @type {number}
     * @memberof StickerPackRo
     */
    'views': number;
    /**
     * 
     * @type {number}
     * @memberof StickerPackRo
     */
    'likes': number;
    /**
     * 
     * @type {string}
     * @memberof StickerPackRo
     */
    'createdAt': string;
    /**
     * 
     * @type {string}
     * @memberof StickerPackRo
     */
    'updatedAt': string;
}

