# Based on: https://github.com/realabbas/Github-Actions-React-Native/blob/master/action.yml

name: Build Release APK
description: "This github action automatically builds the android apk under the artifact section"

on:
  push:
    branches:
      - master
      - ci-build-apk

jobs:
  build-apk:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./app

    steps: 
      - uses: actions/checkout@v2

      - name: Install npm dependencies
        run: |
          npm install

      - name: Build Android Release
        run: |
          cd android && ./gradlew assembleRelease

      - name: Upload Artifact
        uses: actions/upload-artifact@v1
        with:
          name: app-release.apk
          path: android/app/build/outputs/apk/release/

