# Based on: https://github.com/realabbas/Github-Actions-React-Native/blob/master/action.yml

name: Build Release APK

on:
  push:
    branches:
      - master
  pull_request:
    paths:
      - app/*

jobs:
  build-apk:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./app

    env:
      ENVFILE: .env.prod

    steps:
      - uses: actions/checkout@v3

      - name: Set Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16.x

      - name: Run install
        uses: borales/actions-yarn@v4
        with:
          cmd: install

      - name: Build Android Release
        run: |
          cd android && ./gradlew assembleRelease

      - name: Upload Artifact
        uses: actions/upload-artifact@v1
        with:
          name: app-release.apk
          path: app/android/app/build/outputs/apk/release/

