# Based on: https://github.com/realabbas/Github-Actions-React-Native/blob/master/action.yml

name: Build Release APK

on:
  push:
    branches:
      - master
  pull_request:
    branches: 
      - "*"
    paths:
      - app/*

jobs:
  build-apk:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./app
        
    env:
      ENVFILE: .env.prod

    steps: 
      - uses: actions/checkout@v2

      - name: Install npm dependencies
        run: |
          npm install

      - name: Build Android Release
        run: |
          cd android && ./gradlew assembleRelease

      - name: Upload Artifact
        uses: actions/upload-artifact@v1
        with:
          name: app-release.apk
          path: app/android/app/build/outputs/apk/release/

